apiVersion: run.tanzu.vmware.com/v1alpha2
kind: TanzuKubernetesCluster
metadata:
  name: {clustername}
  namespace: {namespace}
spec:
  topology:
    controlPlane:
      replicas: 1
      vmClass: best-effort-small
      storageClass: kubernetes
#      volumes:
#        - name: etcd
#          mountPath: /var/lib/etcd
#          capacity:
#            storage: 4Gi
      tkr:
        reference:
          name: v1.21.2---vmware.1-tkg.1.ee25d55
    nodePools:
    - name: node-pool-1
      replicas: 1
      vmClass: best-effort-small
      storageClass: kubernetes
#      volumes:
#        - name: containerd
#          mountPath: /var/lib/containerd
#          capacity:
#            storage: 30Gi
      tkr:
        reference:
          name: v1.21.2---vmware.1-tkg.1.ee25d55
  settings:
    network:
      cni:
        name: antrea
      pods:
        cidrBlocks: ["192.0.0.0/16"]
      services:
        cidrBlocks: ["198.51.100.0/24"]
    storage:
      classes: ["kubernetes"]
      defaultClass: kubernetes
#    serviceDomain: managedcluster.local
#    proxy:
#      httpProxy: http://<user>:<pwd>@<ip>:<port>
#      httpsProxy: http://<user>:<pwd>@<ip>:<port>
#      noProxy: [10.246.0.0/16,192.168.144.0/20,192.168.128.0/20]
#    trust:
#      additionalTrustedCAs:
#        - name: CompanyInternalCA-1
#          data: LS0tLS1C...LS0tCg==
#        - name: CompanyInternalCA-2
#          data: MTLtMT1C...MT0tPg==
