apiVersion: run.tanzu.vmware.com/v1alpha1    
kind: TanzuKubernetesCluster                 
metadata:
  name: tkc-infra-c01                            #TKG Cluster Nmee                                
  namespace: infra-apps                        #Namespace to deploy cluster to                     
spec:
  distribution:
    version: v1.18.5			         #The full image name is specified 
  topology:
    controlPlane:
      count: 1                                   #Number of control plane nodes                       
      class: best-effort-xsmall                  #Cluster VM size and guaranteed resources or best-effort
      storageClass: kubernetes                 #Specific storage class for control plane       
    workers:
      count: 2                                   #Number of worker nodes                     
      class: best-effort-xsmall                  #Cluster VM size and guaranteed resources or best-effort          
      storageClass: kubernetes                  #Specific storage class for workers     
  settings:
    network:
      services:
        cidrBlocks: ["198.51.100.0/12"]          #Cannot overlap with Supervisor Cluster
      pods:
        cidrBlocks: ["192.0.2.0/16"]             #Cannot overlap with Supervisor Cluster
    storage:
      classes: ["kubernetes"]                   #Named PVC storage classes
      defaultClass: kubernetes                  #Default PVC storage class
