kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: suricata
provisioner: nfs.csi.k8s.io
parameters:
  server: 192.168.79.4
  share: /nfsexport
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - nfsvers=3
