
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dev-cluster-role
rules:
  - apiGroups:
      - ""
      - apps
      - autoscaling
      - batch
      - extensions
      - policy
      - rbac.authorization.k8s.io
    resources:
      - componentstatuses
      - configmaps
      - cronjobs
      - daemonsets
      - deployments
      - deployments/rollback
      - deployments/scale
      - events
      - endpoints
      - horizontalpodautoscalers
      - ingresses
      #- networkpolicies
      - jobs
      - limitranges
      - namespaces
      - nodes
      - poddisruptionbudgets
      - pods
      - pods/attach
      - pods/exec
      - pods/portforward
      - pods/proxy
      - persistentvolumes
      - persistentvolumeclaims
      - replicasets
      - replicasets/scale
      - replicationcontrollers
      - replicationcontrollers/scale
      - secrets
      - serviceaccounts
      - services
      - services/proxy
      - statefulsets
      - statefulsets/scale
      - volumeattachments
    verbs: ["*"]
  - nonResourceURLs: ["*"]
    verbs: ["*"]
  - apiGroups:
    - storage.k8s.io
    resources:
    - storageclasses
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - extensions
    resources:
    - networkpolicies
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - ""
    resources:
    - resourcequotas
    - resourcequotas/status
    verbs:
    - get
    - list
    - watch
