apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rtbsystems:devgroup-ldap-dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dev-cluster-role
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: sso:bauerbo
